#!/bin/bash

# Foundation shell profile setup - runs before all other scripts
set -e

echo "🐚 Setting up shell profile..."

SHELL_PROFILE="$HOME/.zprofile"

# Create .zprofile if it doesn't exist
if [[ ! -f "$SHELL_PROFILE" ]]; then
    echo "Creating $SHELL_PROFILE..."
    touch "$SHELL_PROFILE"
    
    # Add basic header
    echo "# Shell profile for macOS" >> "$SHELL_PROFILE"
    echo "# Auto-generated by chezmoi dotfiles setup" >> "$SHELL_PROFILE"
    echo "" >> "$SHELL_PROFILE"
    
    echo "Created $SHELL_PROFILE"
else
    echo "$SHELL_PROFILE already exists"
fi

echo "🎉 Shell profile setup complete!"
